### ISSUE TITLE
Some more special characters..

### ISSUE THREAD

**Issue by lrsjng** [sindresorhus/escape-string-regexp#1]
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Using_Special_Characters) suggests to also include `=`, `!`, `:` and `/`. Those characters are used for conditional matching. 

Their suggested pattern is `/[.*+?^=!:${}()|\[\]\/\\]/g` (find it below Table 4.1).

Maybe you would like to support those characters too.

**Comment by brettz9** [comment]
Well, technically, you could have something like this though in which case you would want to escape the extra characters:

```js
new RegExp('(?' + esc(str));
```

And following such possibilities, one other character that may need escaping would be `-` in case the context is inside a character class.

**Comment by brettz9** [comment]
Sorry, I guess that was a dumb example, as it would give an error normally, but the case of `-` could occur. Also, `,` ought to be escaped if the context were inside `{}`

**Comment by brettz9** [comment]
Actually, my prior example might even be conceivable if you had a library which allowed unescaped regular expression prefixes on either side of an escape. The following:

```js
function wrap (prefix, str, suffix) {
    new RegExp(prefix + esc(str));
}
var regex = wrap('(?', userStr,  ')');
```

should throw an exception when used to alert the caller to a problem in their prefix, but without escaping `!`, `:`, etc., it may pass.

I know this is pretty unlikely (as is the `{}` example), but I think it's safer just to be comprehensive so there are no surprises no matter the usage.
