### ISSUE TITLE
ES5 file for browser builds

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/escape-string-regexp#16]
```json
"browser": "index-es5.js",
```

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by stevenvachon** [comment]
Running Babel on all dependencies in a big app is painfully slow. I don't think it's much to ask for ES5 files; I do it for all of my projects.
