### ISSUE TITLE
Slash is not escaped (`https://` does not become `https:\/\/`)

### ISSUE THREAD

**Issue by asyncb** [sindresorhus/escape-string-regexp#17]
I may not understand how this package works, since the demo shows double escape for `\\$` as opposed to `\$` as I would expect.

**Comment by sindresorhus** [comment]
> Slash is not escaped (`https://` does not become `https:\/\/`)

```
❯ node
> new RegExp('http://')
/http:\/\//
```

> since the demo shows double escape for \\$ as opposed to \$ as I would expect.

It was accidentally changed in https://github.com/sindresorhus/escape-string-regexp/commit/ea980986c69f1cd8dee3b65597852c6eeaf79430#diff-0730bb7c2e8f9ea2438b52e419dd86c9R19

**Comment by sindresorhus** [comment]
> since the demo shows double escape for \$ as opposed to $ as I would expect.

Actually, that is technically correct, as it shows the output string which does need to be double escaped, even if that's not shown when the string is printed.

**Comment by FDiskas** [comment]
As you would expect it returns corectly escaped string:
```js
String.raw`${new RegExp('http://')}` /* '/http:\\/\\//' */
```
