### ISSUE TITLE
Distributed code contains arrow function that breaks apps on IE11

### ISSUE THREAD

**Issue by ArthurClemens** [sindresorhus/escape-string-regexp#18]
Our app suddenly broke after updating from 1.0.5 to 2.0.0. Since transpilation normally does not happen on code in node_modules, this library was included as-is. Please include a es5 compatible version.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by TheHolyWaffle** [comment]
I'd argue to re-open this. It's industry standard when it comes to frontend development that npm modules are already babelyfied when published. Because, normally people use babel-loader in combination with webpack but exclude node_modules from transpilation.

**Comment by wsmarsh** [comment]
I was using Vue-CLI with this package and it still broke IE11 - your answer to this issue is quite lazy

**Comment by charmander** [comment]
@wsmarsh [`transpileDependencies`](https://cli.vuejs.org/config/#transpiledependencies)

**Comment by wsmarsh** [comment]
Please add to the ReadMe that it only works for NodeJS and not the Browser
