### ISSUE TITLE
Hyphens in Unicode mode

### ISSUE THREAD

**Issue by brettz9** [sindresorhus/escape-string-regexp#20]
With the current behavior of escaping `-`, there is a problem if used in a Unicode regex.

You can see that:

```js
const esc = require('escape-string-regexp');
new RegExp(esc('-'), 'u');
```

gives:

> Invalid regular expression: /\-/: Invalid escape

because this does also:

```js
new RegExp('\\-', 'u');
```

Would seem to call for a Unicode mode? (The hyphen would still need escaping (and be safe to use) within a character class though.)

I don't know whether you'd want to get into such parsing, but just sharing as it is something I came across.

**Comment by sindresorhus** [comment]
How would you escape `-` in Unicode mode?

**Comment by brettz9** [comment]
Yeah, sorry, I was just thinking, it wouldn't make much sense to escape it at all except in an obscure case like:

```js
new RegExp('[' + esc('unsafe-hyphen') + ']');
```

...because `[` would already be escaped if supplying the whole expression to `esc`.

If covering all such obscure cases, one would need to escape (or strip) commas too:

```js
new RegExp('(repeatingSequence){' + esc('1,32') + '}');
```

So I think it should be enough for Unicode mode simply to avoid escaping it at all though of course ensure `[` was escaped.

**Comment by sindresorhus** [comment]
You didn't answer my question. It must be possible to escape `-` somehow in Unicode mode, right?

**Comment by sindresorhus** [comment]
As for dropping escaping `-`, see: https://github.com/sindresorhus/escape-string-regexp/commit/e76291d337900dbfba3b2e04d71c6d718ec7199b

**Comment by brettz9** [comment]
There is no need to escape it in Unicode mode. The solution is *not* to escape it (unless within a character class, and then it is the same as other escapes--with a backslash).

**Comment by charmander** [comment]
`\x2d`

**Comment by brettz9** [comment]
Sure, or `\u002d` or for Unicode mode, `\u{2d}`.

I was just speaking to the fact that the hyphen has never needed to be escaped when outside of a character class (though in non-Unicode mode, an extra backslash would just be ignored--as when preceding other non-special characters with a backslash--e.g., `/\g/` was ok but `/\g/u` will err).

But I guess that does avoid the need for parsing--it should indeed always be safe to replace `-` with a character code/code point escape, no matter within a character class or not. So yeah, a good solution!

**Comment by sindresorhus** [comment]
Awesome. Let's go with that then.

**Comment by brettz9** [comment]
Are you ok with it just being added without needing a special "mode" argument? If someone is doing diffs against the results or something unusual, then it would be a breaking change, but I wouldn't think it would impact that many users.

**Comment by sindresorhus** [comment]
Yes, I'm ok with that. I'll do it as a major release just in case.
