### ISSUE TITLE
Escaping of - not compatible with MongoDB

### ISSUE THREAD

**Issue by marwej** [sindresorhus/escape-string-regexp#22]
I do a MongoDB query like: 

```
const query = {
    email: new RegExp('^' + escapeString(email) + '$', 'i'), // Case insensitive
};
```

In 3.0.0, this is not working with emails containing `-`. Do you know how I could write this using the new way to escape `-`?

**Comment by sindresorhus** [comment]
// @Charmander

**Comment by pcorey** [comment]
I'm also using this library primarily to escape regex MongoDB queries. Any way to opt out of escaping `-` would be great.

**Comment by charmander** [comment]
> Regular expression is invalid: PCRE does not support \\L, \\l, \\N{name}, \\U, or \\u

Going back to the original `\x2d` will work for Mongo support.

**Comment by pcorey** [comment]
Thanks @sindresorhus and @charmander! Just confirmed it's working for me.
