### ISSUE TITLE
ignore Hyphens character

### ISSUE THREAD

**Issue by vndevil** [sindresorhus/escape-string-regexp#27]
In some way, I just don't want escape the Hyphens character, how can I do that, in version 4.0.0 the Hyphens was escaped '-' => '\x2d'

**Comment by sindresorhus** [comment]
Why is it a problem? Please familiarize yourself with why it was needed.

**Comment by Metallou-dev** [comment]
because hyphens can behave like normal characters as explained here

https://stackoverflow.com/questions/4068629/how-to-match-hyphens-with-regular-expression/4068725#4068725

for my needs, i will just wrap your function with a chained call to `.replace(/\\x2d/g, '-')`

**Comment by papb** [comment]
Yes, it is not *always* necessary to escape it, but it doesn't cause any problem if escaped as well. So I also don't see any issue here.

**Comment by charmander** [comment]
> for my needs, i will just wrap your function with a chained call to `.replace(/\\x2d/g, '-')`

@Metallou-dev That will give the wrong result for the input `"\x2d"`.

**Comment by Metallou-dev** [comment]
@charmander agreed. my solution works well **for my needs**
@papb agreed, i just needed to write htaccess directives that seo people can understand (it works but they complain)

**Comment by silverwind** [comment]
I also think the `-` escaping should be only done where necessary, e.g. inside character classes.
