### ISSUE TITLE
add `typings` field to package.json

### ISSUE THREAD

**Issue by KilianKilmister** [sindresorhus/escape-string-regexp#28]
add `"typings": "index.d.ts"` field to `package.json`

without this many tools can not find it

**Comment by sindresorhus** [comment]
The TS docs say it can be left out if it's named `index.d.ts`. It's up to other tools to follow what TS supports.

**Comment by KilianKilmister** [comment]
The TS docs also says to put it in non the less. I find your justification very unreasonable

> Also note that if your main declaration file is named index.d.ts and lives at the root of the package (next to index.js) you do not need to mark the "types" property, though it is advisable to do so.
