### ISSUE TITLE
Support TS default import

### ISSUE THREAD

**Issue by KilianKilmister** [sindresorhus/escape-string-regexp#29]
Quoting from #28:

> It's up to other tools to follow what TS supports.

TS also suports default imports, but yout packages definition sais it doesn't

**Comment by sindresorhus** [comment]
This is a CommonJS package (like most packages on npm), so it's recommended you use the require syntax for that. However, there are TS settings to override it and let you use normal import syntax with this package too. I'm following the [advice](https://github.com/sindresorhus/mem/issues/31) of the TS team on this.

**Comment by KilianKilmister** [comment]
I read the thread and yeah, it sounds reaonable
