### ISSUE TITLE
Forward slash is not escaped

### ISSUE THREAD

**Issue by septagram** [sindresorhus/escape-string-regexp#30]
```
igornovikov1@~/Documents/Code/wtf-test:$ npm i escape-string-regexp
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN wtf-test@1.0.0 No description
npm WARN wtf-test@1.0.0 No repository field.

+ escape-string-regexp@4.0.0
added 1 package from 1 contributor and audited 1 package in 2.12s
found 0 vulnerabilities

igornovikov1@~/Documents/Code/wtf-test:$ node
> const escape = require('escape-string-regexp')
undefined
> escape ('^test/test$')
'\\^test/test\\$'
```

**Comment by papb** [comment]
Why should it? Running `new RegExp('\\^test/test\\$')` works fine.

**Comment by septagram** [comment]
I suppose this is reasonable, but I'd appreciate highlighting it in the docs. My case is a little unusual, I'm passing the regexp into the `DefinePlugin` in order to use the regexp as a `require.context` argument -- otherwise non-matching files would be compiled anyway. So, I wrongly expected the slashes to be escaped and ended up with an incredibly arcane error a few weeks later.

**Comment by sindresorhus** [comment]
Package description:

> Escape **RegExp special characters**

It would be both surprising and incorrect if we escaped other characters.

**Comment by sindresorhus** [comment]
I guess we could make it clearer in the readme that only the minimal amount of escaping is done.

**Comment by septagram** [comment]
Thanks, that would work :)
