### ISSUE TITLE
Version 5.0 doesn't play nice when doing a Vercel deploy

### ISSUE THREAD

**Issue by jaytula** [sindresorhus/escape-string-regexp#33]
The errors are in red. I switched to version 4.0 and it builds.

![image](https://user-images.githubusercontent.com/75389/117885928-5a371d80-b263-11eb-9874-dfb50fe7779a.png)

Maybe try removing `"type": "module"` from *package.json* as suggested.

I will happily retry. 🦄

**Comment by zkldi** [comment]
Also getting this error under tsnode with node v15.9.0, ts-node v9.1.1.

**Comment by sindresorhus** [comment]
It's all the in the release notes. Feel free to copy-paste the code.
