### ISSUE TITLE
Can't use this with typescript/node16?

### ISSUE THREAD

**Issue by TomMettam** [sindresorhus/escape-string-regexp#37]
`import escapeStringRegexp from 'escape-string-regexp';`

Typescript compiles this down to

`const escape_string_regexp_1 = require("escape-string-regexp");`

which causes Node to throw

```
[ERROR] uncaughtException: require() of ES Module node_modules\escape-string-regexp\index.js from dist\backend\classes\UiClient.js not supported.
Instead change the require of index.js in dist\backend\classes\UiClient.js to a dynamic import() which is available in all CommonJS modules.
```

I don't have this issue with any other module; how can I work around this?

**Comment by brioapp** [comment]
same issue here, node 14 + typescript

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by TomMettam** [comment]
Unfortunately, `await import(…)` doesn't work either with Typescript (it compiles it to a require, even when targeting es2020).

And given that very few other node modules are compatible with ES6, this basically means that you cannot use this module with node + typescript.

Fortunately this module basically consists of just one line of code so I copied it into my project - problem solved.

**Comment by olchyk98** [comment]
There's no essential difference between `v4` and `v5`, except of the fact that `v4` is not ESM. Downgrading the package to `v4` should resolve the issue for now.
