### ISSUE TITLE
Simple Hyphen-Minus should not be escaped

### ISSUE THREAD

**Issue by tyge68** [sindresorhus/escape-string-regexp#39]
Currently if you escape a string with Hyphen-Minus in it it get converted to some \\x2d which is then not working once executing the regexp search (for example with postgresql regexp_replace(....) which accept regexp.

I am not sure if that is an issue in postgresql or in this library, still to me it doesn't seem like minus would actually need to be escaped.
Example:
```
escapeRegExp('some-value-to-escape')
```
it returns 'some\\x2dvalue\\x2dto\\x2descape' which is not really required for regexp I think, but maybe I am wrong.
In any cases I couldn't then use this library for my usecase.

**Comment by charmander** [comment]
`\x2d` should work fine in PostgreSQL’s `regexp_replace`. How are you using it?

> ```sql
> SELECT regexp_replace('foo-bar-baz', '\x2d', '_', 'g');
> ```
> 
> | regexp_replace |
> |----------------|
> | foo_bar_baz |

It requires escaping in general when used in character classes (`[chars]`).

**Comment by stevenliebregt** [comment]
It does not seem to work with `regexp_match` for me on Postgres

The following:

```sql
select 
	regexp_match('foo-bar-baz', 'foo\x2dbar\x2dbaz') AS escaped,
	regexp_match('foo-bar-baz', 'foo-bar-baz') AS not_escaped
```

Yields

![image](https://github.com/user-attachments/assets/23dd3713-602f-4036-a975-9ce60859c0d1)

**Comment by charmander** [comment]
@stevenliebregt My mistake – this isn’t compatible with PostgreSQL regular expressions. https://www.postgresql.org/docs/current/functions-matching.html#POSIX-SYNTAX-DETAILS

> Regular expressions (REs), as defined in POSIX 1003.2, come in two forms: extended REs or EREs (roughly those of egrep), and basic REs or BREs (roughly those of ed). PostgreSQL supports both forms, **and also implements some extensions that are not in the POSIX standard, but have become widely used due to their availability in programming languages such as Perl and Tcl. REs using these non-POSIX extensions are called advanced REs or AREs** in this documentation.

https://www.postgresql.org/docs/current/functions-matching.html#POSIX-ESCAPE-SEQUENCES

> | Escape | Description |
> |---|---|
> | `\xhhh` | (where `hhh` is any sequence of hexadecimal digits) the character whose hexadecimal value is `0xhhh` (a single character **no matter how many hexadecimal digits are used**) |
