### ISSUE TITLE
Come help us!

### ISSUE THREAD

**Issue by benjamingr** [sindresorhus/escape-string-regexp#7]
Hey, so I'm currently working on adding an escape function to the language at https://github.com/benjamingr/RexExp.escape 

There is discussion tag for issues https://github.com/benjamingr/RexExp.escape/labels/discussion%20appreciated 

As a library that does this - I'd appreciate your opinion and take on what characters need to be escaped (we're currently debating `/` but I can definitely see `-` around the corner).

**Comment by jbnicolai** [comment]
Late reply, as I'm only just returning from a holiday - but I'd love to @benjamingr!

**Comment by sindresorhus** [comment]
Will take a look too :)
